### ISSUE TITLE
Directory-level approval configuration

### ISSUE THREAD

**Issue by marshall7m** [marshall7m/terraform-aws-infrastructure-live-ci#18]
Allow users to define a config file such as `approval_ci.yaml` within each Terraform directory that contains directory-level approval configurations. This allows PR contributors to dynamically set these configurations within their PR rather than relying on the default configuration specified as input in this Terraform module.

The config file can look something like this:
```
include_parent: true
voters:
  John:
    email: john@company.com
    sms: 123-456-7890
    slack: john123
    notify_on:
    - failure
    - success
min_approval_count: 2
min_rejection_count: 2
```

`include_parent: true` will result in the first parent `approval_ci.yaml` configuration being merged with the child configuration (inspired by Terragrunt [include block](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#find_in_parent_folders))
